// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanesTuristicos.Models;

#nullable disable

namespace PlanesTuristicos.Migrations
{
    [DbContext(typeof(PlanesTuristicosContext))]
    [Migration("20240501230800_nvnvnvnvv")]
    partial class nvnvnvnvv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanesTuristicos.Models.PlanesT", b =>
                {
                    b.Property<int>("Id_PlanTuristicos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PlanTuristicos"));

                    b.Property<int?>("Actividades")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Actividades");

                    b.Property<string>("Duracion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Duracion");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Imagen");

                    b.Property<string>("Informacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Informacion");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Municipio");

                    b.Property<string>("Nombre_PlanTuristico")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_PlanTuristico");

                    b.Property<decimal>("Precio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Precio");

                    b.Property<int?>("Rut")
                        .HasColumnType("int")
                        .HasColumnName("Rut");

                    b.HasKey("Id_PlanTuristicos")
                        .HasName("PK__PlanesT__Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("PlanesT", (string)null);
                });

            modelBuilder.Entity("PlanesTuristicos.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"));

                    b.Property<int?>("Cedula")
                        .HasColumnType("int")
                        .HasColumnName("cedula");

                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo");

                    b.Property<int?>("Rut")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Rut");

                    b.Property<string>("direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("nombreProveedor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_turista");

                    b.HasKey("Id_Proveedor")
                        .HasName("PK__Proveedores__Id");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("PlanesTuristicos.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Actividades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlanTuristico")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Informacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePlanTuristico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("TelefonoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdPlanTuristico");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PlanesTuristicos.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cedula");

                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("NombreTurista")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_turista");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF971AB28277");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("PlanesTuristicos.Models.PlanesT", b =>
                {
                    b.HasOne("PlanesTuristicos.Models.Proveedor", "Proveedor")
                        .WithMany("Planes")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PlanesTuristicos.Models.Reserva", b =>
                {
                    b.HasOne("PlanesTuristicos.Models.PlanesT", "PlanTuristico")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPlanTuristico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_PlanesT");

                    b.Navigation("PlanTuristico");
                });

            modelBuilder.Entity("PlanesTuristicos.Models.PlanesT", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PlanesTuristicos.Models.Proveedor", b =>
                {
                    b.Navigation("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
